platform :ios, '12.0'

target 'AdsRepo_Example' do
  pod 'AdsRepo', :path => '../', :testspecs => ['Tests']

#  pod 'Google-Mobile-Ads-SDK'
  
  target 'AdsRepo_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
