platform :ios, '11.0'

target 'AdsRepo_Example' do
  pod 'AdsRepo', :path => '../', :testspecs => ['Tests']

  target 'AdsRepo_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
